# This workflow is only for inclusion in other workflows.
name: Deploy via ssh
on:
  workflow_call:
    inputs:
      VERSION:
        description: "Version to deploy (dockerhub tag)"
        required: false
        default: "main"
        type: string
      CONTAINER_NAME:
        description: "Container name"
        default: "aepp-bridge-and-swap"
        required: false
        type: string
    secrets:
      DEPLOY_HOST:
        description: "Host to deploy to"
        required: true
      DEPLOY_USERNAME:
        description: "Username to use for ssh"
        required: true
      DEPLOY_KEY:
        description: "SSH key to use for ssh"
        required: true
      HOST_PORT:
        description: "Host port to expose"
        required: true
      NEXT_PUBLIC_AE_PRIVATE_KEY:
        description: "NEXT_PUBLIC_AE_PRIVATE_KEY"
        required: true
      NEXT_PUBLIC_MAINNET:
        description: "NEXT_PUBLIC_MAINNET"
        required: true
      NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID:
        description: "NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID"
        required: true
jobs:
  deploy:
    name: Deploy via ssh
    runs-on: ubuntu-latest
    steps:
      - name: Run deploy script
        uses: appleboy/ssh-action@v1.0.0
        env:
          VERSION: "${{ inputs.VERSION }}"
          SHA: "${{ github.sha }}"
          NEXT_PUBLIC_AE_PRIVATE_KEY: "${{ secrets.NEXT_PUBLIC_AE_PRIVATE_KEY }}"
          NEXT_PUBLIC_MAINNET: "${{ secrets.NEXT_PUBLIC_MAINNET }}"
          NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: "${{ secrets.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID }}"
          HOST_DATA_DIR: "./${{ inputs.CONTAINER_NAME }}"
          HOST_PORT: "${{ secrets.HOST_PORT }}"
        with:
          host: "${{ secrets.DEPLOY_HOST }}"
          username: "${{ secrets.DEPLOY_USERNAME }}"
          key: "${{ secrets.DEPLOY_KEY }}"
          envs: >
            HOST_DATA_DIR,
            NEXT_PUBLIC_AE_PRIVATE_KEY,
            NEXT_PUBLIC_MAINNET,
            NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID,
            SHA
          script: |
            echo $SHA > $HOST_DATA_DIR/REVISION || true
            docker pull "aeternity/aepp-bridge-and-swap:${{ inputs.VERSION }}" || true
            docker stop ${{ inputs.CONTAINER_NAME }} || true
            docker rm ${{ inputs.CONTAINER_NAME }} || true
            docker run -d --name ${{ inputs.CONTAINER_NAME }} \
              --restart=always \
              -p ${{ secrets.HOST_PORT }}:3000 \
              -e APP_PORT="3000" \
              -e NEXT_PUBLIC_AE_PRIVATE_KEY="${{ secrets.NEXT_PUBLIC_AE_PRIVATE_KEY }}" \
              -e NEXT_PUBLIC_MAINNET="${{ secrets.NEXT_PUBLIC_MAINNET }}" \
              -e NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID="${{ secrets.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID }}" \
              -e NODE_ENV=production \
              aeternity/aepp-bridge-and-swap:${{ inputs.VERSION }}
